class AddShottypesToShottype < ActiveRecord::Migration
	SHOTS = [
		{:shottype => 'Backfoot Cover Drive'},
		{:shottype => 'Backfoot Defence'},
		{:shottype => 'Backfoot Glance'},
		{:shottype => 'Backfoot On Drive'},
		{:shottype => 'Backfoot Off Drive'},
		{:shottype => 'Backfoot Straight Drive'},
		{:shottype => 'Beaten'},
		{:shottype => 'Cover Drive'},
		{:shottype => 'Defence'},
		{:shottype => 'Edge'},
		{:shottype => 'Extra Cover Drive'},
		{:shottype => 'Flick'},
		{:shottype => 'Glance'},
		{:shottype => 'Guided Shot'},
		{:shottype => 'Hook'},
		{:shottype => 'Late Cut'},
		{:shottype => 'Leave'},
		{:shottype => 'Lofted Cover Drive'},
		{:shottype => 'Lofted Extra Cover Drive'},
		{:shottype => 'Lofted Flick'},
		{:shottype => 'Lofted Off Drive'},
		{:shottype => 'Lofted On Drive'},
		{:shottype => 'Lofted Over Slip'},
		{:shottype => 'Lofted Pull'},
		{:shottype => 'Lofted Square Cut'},
		{:shottype => 'Lofted Square Drive'},
		{:shottype => 'Lofted Straight Drive'},
		{:shottype => 'Miss Hit Cover Drive'},
		{:shottype => 'Miss Hit Extra Cover Drive'},
		{:shottype => 'Miss Hit Flick'},
		{:shottype => 'Miss Hit Glance'},
		{:shottype => 'Miss Hit Hook'},
		{:shottype => 'Miss Hit Off Drive'},
		{:shottype => 'Miss Hit On Drive'},
		{:shottype => 'Miss Hit Paddle Sweep'},
		{:shottype => 'Miss Hit Pull'},
		{:shottype => 'Miss Hit Reverse Sweep'},
		{:shottype => 'Miss Hit Scoop'},
		{:shottype => 'Miss Hit Square Cut'},
		{:shottype => 'Miss Hit Square Drive'},
		{:shottype => 'Miss Hit Straight Drive'},
		{:shottype => 'Miss Hit Sweep'},
		{:shottype => 'Miss Hit Switch Hit'},
		{:shottype => 'On Drive'},
		{:shottype => 'Off Drive'},
		{:shottype => 'Paddle Sweep'},
		{:shottype => 'Grounded Pull'},
		{:shottype => 'Reverse Sweep'},
		{:shottype => 'Scoop'},
		{:shottype => 'Slug'},
		{:shottype => 'Slug Sweep'},
		{:shottype => 'Square Cut'},
		{:shottype => 'Square Drive'},
		{:shottype => 'Straight Drive'},
		{:shottype => 'Sweep'},
		{:shottype => 'Switch Hit'},
		{:shottype => 'Tap'}
	]
	def change
		SHOTS.each do |s|
			st=Shottype.create(s)
			st.save
		end
	end
end
